### ISSUE TITLE
Olá amigo.

### ISSUE THREAD

**Issue by ManoelSantos** [joomlapro/pkg_polls#3]
Não sou expert em programação, mas sou um apaixonado por Joomla. mantenho na rede dois sites baseados neste maravilhoso e apaixonante CMS desde a sua primeira versão.
Uma das ausência muito sentida nesta nova versão é o módulo de pesquisa (POLL) retirado após a versão 1.59. Uma pena.
As que existem free e pagas pecam pelo excesso de mau gosto e por configurações exageradas e, a meu modo de ver, desnecessárias. Sou optante da simplicidade, primeiro para não por em risco a segurança dos meus sites, depois pela facilidade de uso o que era extremamente importante do componente POLL inexplicavelmente retirado das novas versões do Joomla.
Estou começando a pesquisar o uso do Sublim Text 3. Estou estudando tutoriais que se encontram fartamente na net. para, como leigo em programação que sou, usar das facilidade deste editor para reformular o antigo módulo POLL do Joomla.
Baixei seu módulo de pesquisa para testar em localhost. Porém quando tento habilitar o módulo,
apresenta o seguinte erro: Invalid field:  MOD_POLLS_FIELD_POLL_LABEL 
Quando mudo esta label para algo como poll_1
Apresenta vários erros:
1) Trying to get property of non-object in C:\wamp\www\Teste polls\libraries\cms\form\field\ordering.php on line 155
2) Notice: Undefined variable: ordering in C:\wamp\www\Teste polls\libraries\cms\form\field\ordering.php on line 170
3) Notice: Trying to get property of non-object in C:\wamp\www\Teste polls\libraries\cms\form\field\ordering.php on line 171
4) Warning: Invalid argument supplied for foreach() in C:\wamp\www\Teste polls\libraries\joomla\database\driver.php on line 1527
E, abaixo destes erros, aparece o editor de texto.

Podes dar uma ajuda para este iniciante curioso em progração?
Meu email: mgsant12@gmail.com

**Comment by brunowego** [comment]
@ManoelSantos assim que tiver um tempo a noite, vou tentar resolver esse problema e lhe aviso.

**Comment by brunowego** [comment]
Qual versão do Joomla! está utilizando?

**Comment by ManoelSantos** [comment]
3.4.5.

**Comment by brunowego** [comment]
Bom, o componente foi feito para versão do Joomla! 3.1, teve mudanças na plataforma. É preciso corrigir esses bugs, infelizmente eu não estou mais ativo no desenvolvimento para Joomla!.

**Comment by ManoelSantos** [comment]
Uma pena Bruno. Como disse, não entendo muito de programação. Estou tentando aprender aos 63 anos de idade (rsrsrsrsrs). Mas valeu.
Caso vc decida o contrário ou queira me dar uma luz aqui vai o erro mostrado na área de administração:


( ! ) Notice: Trying to get property of non-object in C:\wamp\www\Teste polls\libraries\cms\form\field\ordering.php on line 155
Call Stack
#	Time	Memory	Function	Location
1	0.0004	140632	{main}( )	..\index.php:0
2	0.0707	2322896	JApplicationCms->execute( )	..\index.php:47
3	0.0707	2323048	JApplicationAdministrator->doExecute( )	..\cms.php:252
4	0.1201	3590376	JApplicationAdministrator->dispatch( )	..\administrator.php:152
5	0.1241	3683768	JComponentHelper::renderComponent( )	..\administrator.php:98
6	0.1280	3715656	JComponentHelper::executeComponent( )	..\helper.php:372
7	0.1284	3736640	require_once( 'C:\wamp\www\Teste polls\administrator\components\com_polls\polls.php' )	..\helper.php:392
8	0.1341	3928440	JControllerLegacy->execute( )	..\polls.php:20
9	0.1341	3928560	PollsController->display( )	..\legacy.php:728
10	0.1351	3941744	JControllerLegacy->display( )	..\controller.php:56
11	0.2298	4574752	PollsViewPoll->display( )	..\legacy.php:690
12	0.3469	5458344	JViewLegacy->display( )	..\view.html.php:55
13	0.3470	5458600	JViewLegacy->loadTemplate( )	..\legacy.php:209
14	0.4843	5530720	include( 'C:\wamp\www\Teste polls\administrator\components\com_polls\views\poll\tmpl\edit.php' )	..\legacy.php:670
15	0.9566	6915152	JForm->getInput( )	..\edit.php:114
16	0.9580	6915056	JFormFieldOrdering->__get( )	..\edit.php:558
17	0.9580	6915056	JFormField->__get( )	..\ordering.php:52
18	0.9580	6915216	JFormFieldOrdering->getInput( )	..\field.php:393
19	0.9581	6915640	JFormFieldOrdering->getQuery( )	..\ordering.php:126


( ! ) Notice: Trying to get property of non-object in C:\wamp\www\Teste polls\libraries\cms\form\field\ordering.php on line 155
Call Stack
#	Time	Memory	Function	Location
1	0.0004	140632	{main}( )	..\index.php:0
2	0.0707	2322896	JApplicationCms->execute( )	..\index.php:47
3	0.0707	2323048	JApplicationAdministrator->doExecute( )	..\cms.php:252
4	0.1201	3590376	JApplicationAdministrator->dispatch( )	..\administrator.php:152
5	0.1241	3683768	JComponentHelper::renderComponent( )	..\administrator.php:98
6	0.1280	3715656	JComponentHelper::executeComponent( )	..\helper.php:372
7	0.1284	3736640	require_once( 'C:\wamp\www\Teste polls\administrator\components\com_polls\polls.php' )	..\helper.php:392
8	0.1341	3928440	JControllerLegacy->execute( )	..\polls.php:20
9	0.1341	3928560	PollsController->display( )	..\legacy.php:728
10	0.1351	3941744	JControllerLegacy->display( )	..\controller.php:56
11	0.2298	4574752	PollsViewPoll->display( )	..\legacy.php:690
12	0.3469	5458344	JViewLegacy->display( )	..\view.html.php:55
13	0.3470	5458600	JViewLegacy->loadTemplate( )	..\legacy.php:209
14	0.4843	5530720	include( 'C:\wamp\www\Teste polls\administrator\components\com_polls\views\poll\tmpl\edit.php' )	..\legacy.php:670
15	0.9566	6915152	JForm->getInput( )	..\edit.php:114
16	0.9580	6915056	JFormFieldOrdering->__get( )	..\edit.php:558
17	0.9580	6915056	JFormField->__get( )	..\ordering.php:52
18	0.9580	6915216	JFormFieldOrdering->getInput( )	..\field.php:393
19	0.9581	6915640	JFormFieldOrdering->getQuery( )	..\ordering.php:126


( ! ) Notice: Undefined variable: ordering in C:\wamp\www\Teste polls\libraries\cms\form\field\ordering.php on line 170
Call Stack
#	Time	Memory	Function	Location
1	0.0004	140632	{main}( )	..\index.php:0
2	0.0707	2322896	JApplicationCms->execute( )	..\index.php:47
3	0.0707	2323048	JApplicationAdministrator->doExecute( )	..\cms.php:252
4	0.1201	3590376	JApplicationAdministrator->dispatch( )	..\administrator.php:152
5	0.1241	3683768	JComponentHelper::renderComponent( )	..\administrator.php:98
6	0.1280	3715656	JComponentHelper::executeComponent( )	..\helper.php:372
7	0.1284	3736640	require_once( 'C:\wamp\www\Teste polls\administrator\components\com_polls\polls.php' )	..\helper.php:392
8	0.1341	3928440	JControllerLegacy->execute( )	..\polls.php:20
9	0.1341	3928560	PollsController->display( )	..\legacy.php:728
10	0.1351	3941744	JControllerLegacy->display( )	..\controller.php:56
11	0.2298	4574752	PollsViewPoll->display( )	..\legacy.php:690
12	0.3469	5458344	JViewLegacy->display( )	..\view.html.php:55
13	0.3470	5458600	JViewLegacy->loadTemplate( )	..\legacy.php:209
14	0.4843	5530720	include( 'C:\wamp\www\Teste polls\administrator\components\com_polls\views\poll\tmpl\edit.php' )	..\legacy.php:670
15	0.9566	6915152	JForm->getInput( )	..\edit.php:114
16	0.9580	6915056	JFormFieldOrdering->__get( )	..\edit.php:558
17	0.9580	6915056	JFormField->__get( )	..\ordering.php:52
18	0.9580	6915216	JFormFieldOrdering->getInput( )	..\field.php:393
19	0.9581	6915640	JFormFieldOrdering->getQuery( )	..\ordering.php:126


( ! ) Notice: Undefined variable: title in C:\wamp\www\Teste polls\libraries\cms\form\field\ordering.php on line 170
Call Stack
#	Time	Memory	Function	Location
1	0.0004	140632	{main}( )	..\index.php:0
2	0.0707	2322896	JApplicationCms->execute( )	..\index.php:47
3	0.0707	2323048	JApplicationAdministrator->doExecute( )	..\cms.php:252
4	0.1201	3590376	JApplicationAdministrator->dispatch( )	..\administrator.php:152
5	0.1241	3683768	JComponentHelper::renderComponent( )	..\administrator.php:98
6	0.1280	3715656	JComponentHelper::executeComponent( )	..\helper.php:372
7	0.1284	3736640	require_once( 'C:\wamp\www\Teste polls\administrator\components\com_polls\polls.php' )	..\helper.php:392
8	0.1341	3928440	JControllerLegacy->execute( )	..\polls.php:20
9	0.1341	3928560	PollsController->display( )	..\legacy.php:728
10	0.1351	3941744	JControllerLegacy->display( )	..\controller.php:56
11	0.2298	4574752	PollsViewPoll->display( )	..\legacy.php:690
12	0.3469	5458344	JViewLegacy->display( )	..\view.html.php:55
13	0.3470	5458600	JViewLegacy->loadTemplate( )	..\legacy.php:209
14	0.4843	5530720	include( 'C:\wamp\www\Teste polls\administrator\components\com_polls\views\poll\tmpl\edit.php' )	..\legacy.php:670
15	0.9566	6915152	JForm->getInput( )	..\edit.php:114
16	0.9580	6915056	JFormFieldOrdering->__get( )	..\edit.php:558
17	0.9580	6915056	JFormField->__get( )	..\ordering.php:52
18	0.9580	6915216	JFormFieldOrdering->getInput( )	..\field.php:393
19	0.9581	6915640	JFormFieldOrdering->getQuery( )	..\ordering.php:126


( ! ) Notice: Trying to get property of non-object in C:\wamp\www\Teste polls\libraries\cms\form\field\ordering.php on line 171
Call Stack
#	Time	Memory	Function	Location
1	0.0004	140632	{main}( )	..\index.php:0
2	0.0707	2322896	JApplicationCms->execute( )	..\index.php:47
3	0.0707	2323048	JApplicationAdministrator->doExecute( )	..\cms.php:252
4	0.1201	3590376	JApplicationAdministrator->dispatch( )	..\administrator.php:152
5	0.1241	3683768	JComponentHelper::renderComponent( )	..\administrator.php:98
6	0.1280	3715656	JComponentHelper::executeComponent( )	..\helper.php:372
7	0.1284	3736640	require_once( 'C:\wamp\www\Teste polls\administrator\components\com_polls\polls.php' )	..\helper.php:392
8	0.1341	3928440	JControllerLegacy->execute( )	..\polls.php:20
9	0.1341	3928560	PollsController->display( )	..\legacy.php:728
10	0.1351	3941744	JControllerLegacy->display( )	..\controller.php:56
11	0.2298	4574752	PollsViewPoll->display( )	..\legacy.php:690
12	0.3469	5458344	JViewLegacy->display( )	..\view.html.php:55
13	0.3470	5458600	JViewLegacy->loadTemplate( )	..\legacy.php:209
14	0.4843	5530720	include( 'C:\wamp\www\Teste polls\administrator\components\com_polls\views\poll\tmpl\edit.php' )	..\legacy.php:670
15	0.9566	6915152	JForm->getInput( )	..\edit.php:114
16	0.9580	6915056	JFormFieldOrdering->__get( )	..\edit.php:558
17	0.9580	6915056	JFormField->__get( )	..\ordering.php:52
18	0.9580	6915216	JFormFieldOrdering->getInput( )	..\field.php:393
19	0.9581	6915640	JFormFieldOrdering->getQuery( )	..\ordering.php:126


( ! ) Notice: Trying to get property of non-object in C:\wamp\www\Teste polls\libraries\cms\form\field\ordering.php on line 171
Call Stack
#	Time	Memory	Function	Location
1	0.0004	140632	{main}( )	..\index.php:0
2	0.0707	2322896	JApplicationCms->execute( )	..\index.php:47
3	0.0707	2323048	JApplicationAdministrator->doExecute( )	..\cms.php:252
4	0.1201	3590376	JApplicationAdministrator->dispatch( )	..\administrator.php:152
5	0.1241	3683768	JComponentHelper::renderComponent( )	..\administrator.php:98
6	0.1280	3715656	JComponentHelper::executeComponent( )	..\helper.php:372
7	0.1284	3736640	require_once( 'C:\wamp\www\Teste polls\administrator\components\com_polls\polls.php' )	..\helper.php:392
8	0.1341	3928440	JControllerLegacy->execute( )	..\polls.php:20
9	0.1341	3928560	PollsController->display( )	..\legacy.php:728
10	0.1351	3941744	JControllerLegacy->display( )	..\controller.php:56
11	0.2298	4574752	PollsViewPoll->display( )	..\legacy.php:690
12	0.3469	5458344	JViewLegacy->display( )	..\view.html.php:55
13	0.3470	5458600	JViewLegacy->loadTemplate( )	..\legacy.php:209
14	0.4843	5530720	include( 'C:\wamp\www\Teste polls\administrator\components\com_polls\views\poll\tmpl\edit.php' )	..\legacy.php:670
15	0.9566	6915152	JForm->getInput( )	..\edit.php:114
16	0.9580	6915056	JFormFieldOrdering->__get( )	..\edit.php:558
17	0.9580	6915056	JFormField->__get( )	..\ordering.php:52
18	0.9580	6915216	JFormFieldOrdering->getInput( )	..\field.php:393
19	0.9581	6915640	JFormFieldOrdering->getQuery( )	..\ordering.php:126


( ! ) Notice: Trying to get property of non-object in C:\wamp\www\Teste polls\libraries\cms\form\field\ordering.php on line 171
Call Stack
#	Time	Memory	Function	Location
1	0.0004	140632	{main}( )	..\index.php:0
2	0.0707	2322896	JApplicationCms->execute( )	..\index.php:47
3	0.0707	2323048	JApplicationAdministrator->doExecute( )	..\cms.php:252
4	0.1201	3590376	JApplicationAdministrator->dispatch( )	..\administrator.php:152
5	0.1241	3683768	JComponentHelper::renderComponent( )	..\administrator.php:98
6	0.1280	3715656	JComponentHelper::executeComponent( )	..\helper.php:372
7	0.1284	3736640	require_once( 'C:\wamp\www\Teste polls\administrator\components\com_polls\polls.php' )	..\helper.php:392
8	0.1341	3928440	JControllerLegacy->execute( )	..\polls.php:20
9	0.1341	3928560	PollsController->display( )	..\legacy.php:728
10	0.1351	3941744	JControllerLegacy->display( )	..\controller.php:56
11	0.2298	4574752	PollsViewPoll->display( )	..\legacy.php:690
12	0.3469	5458344	JViewLegacy->display( )	..\view.html.php:55
13	0.3470	5458600	JViewLegacy->loadTemplate( )	..\legacy.php:209
14	0.4843	5530720	include( 'C:\wamp\www\Teste polls\administrator\components\com_polls\views\poll\tmpl\edit.php' )	..\legacy.php:670
15	0.9566	6915152	JForm->getInput( )	..\edit.php:114
16	0.9580	6915056	JFormFieldOrdering->__get( )	..\edit.php:558
17	0.9580	6915056	JFormField->__get( )	..\ordering.php:52
18	0.9580	6915216	JFormFieldOrdering->getInput( )	..\field.php:393
19	0.9581	6915640	JFormFieldOrdering->getQuery( )	..\ordering.php:126


( ! ) Warning: Invalid argument supplied for foreach() in C:\wamp\www\Teste polls\libraries\joomla\database\driver.php on line 1527
Call Stack
#	Time	Memory	Function	Location
1	0.0004	140632	{main}( )	..\index.php:0
2	0.0707	2322896	JApplicationCms->execute( )	..\index.php:47
3	0.0707	2323048	JApplicationAdministrator->doExecute( )	..\cms.php:252
4	0.1201	3590376	JApplicationAdministrator->dispatch( )	..\administrator.php:152
5	0.1241	3683768	JComponentHelper::renderComponent( )	..\administrator.php:98
6	0.1280	3715656	JComponentHelper::executeComponent( )	..\helper.php:372
7	0.1284	3736640	require_once( 'C:\wamp\www\Teste polls\administrator\components\com_polls\polls.php' )	..\helper.php:392
8	0.1341	3928440	JControllerLegacy->execute( )	..\polls.php:20
9	0.1341	3928560	PollsController->display( )	..\legacy.php:728
10	0.1351	3941744	JControllerLegacy->display( )	..\controller.php:56
11	0.2298	4574752	PollsViewPoll->display( )	..\legacy.php:690
12	0.3469	5458344	JViewLegacy->display( )	..\view.html.php:55
13	0.3470	5458600	JViewLegacy->loadTemplate( )	..\legacy.php:209
14	0.4843	5530720	include( 'C:\wamp\www\Teste polls\administrator\components\com_polls\views\poll\tmpl\edit.php' )	..\legacy.php:670
15	0.9566	6915152	JForm->getInput( )	..\edit.php:114
16	0.9580	6915056	JFormFieldOrdering->__get( )	..\edit.php:558
17	0.9580	6915056	JFormField->__get( )	..\ordering.php:52
18	0.9580	6915216	JFormFieldOrdering->getInput( )	..\field.php:393
19	0.9581	6915640	JFormFieldOrdering->getQuery( )	..\ordering.php:126
20	3.3973	6994424	JDatabaseDriver->quoteName( )	..\ordering.php:171
